nelmio_api_doc:
    documentation:
        info:
            title: My API Bilemo
            description: This is an awesome api !
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
        - ^/api(?!/json$)
        - ^/api(?!/doc$)
